### ISSUE TITLE
Pattern matching behavior changed / is partially broken

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/firewall-controller#145]
With the https://github.com/metal-stack/firewall-controller/pull/137, the test case from our integration environment does not work anymore:

```
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-5000-with-match-pattern-2
  namespace: firewall
spec:
  egress:
  - ports:
    - port: 5000
      protocol: TCP
    toFQDNs:
    - matchPattern: "ww*.<name>.org"
```

But when changing the policy to the following, it works:

```
apiVersion: metal-stack.io/v1
kind: ClusterwideNetworkPolicy
metadata:
  name: allow-5000-with-match-pattern-2
  namespace: firewall
spec:
  egress:
  - ports:
    - port: 5000
      protocol: TCP
    toFQDNs:
    - matchPattern: "*.<name>.org"
```
