### ISSUE TITLE
rule counter names are a bit mangled

### ISSUE THREAD

**Issue by majst01** [metal-stack/firewall-controller#21]
```
  stats:                                                                                                                                                                                                                                                                                  
    rules:                                                                                                                                                                                                                                                                                
      accept:                                                                                                                                                                                                                                                                             
        "accept established connections\0":                                                                                                                                                                                                                                               
          counter:                                                                                                                                                                                                                                                                        
            bytes: 0                                                                                                                                                                                                                                                                      
            packets: 0                                                                                                                                                                                                                                                                    
        "accept icmp\0":                                                                                                                                                                                                                                                                  
          counter:                                                                                                                                                                                                                                                                        
            bytes: 0
            packets: 0
        "accept traffic for k8s service firewall/s1\0":
          counter:
            bytes: 0
            packets: 0
        "accept traffic for np clusterwidenetworkpolicy-sample tcp\0": 
          counter:
            bytes: 0
            packets: 0
        "accept traffic for np clusterwidenetworkpolicy-sample udp\0": 
          counter:
            bytes: 0
            packets: 0
      drop:
        "drop packets with invalid ct state\0":
          counter:
            bytes: 0
            packets: 0
```

They seem to be "\0" terminated, this should be removed.
