### ISSUE TITLE
droptailer connect not working

### ISSUE THREAD

**Issue by mwennrich** [metal-stack/firewall-controller#72]
```
Feb 11 19:36:24 shoot--p5mlcn--<masked>-firewall-eeeb8 ip[1412]: 2021/02/11 19:36:24 unable to send dropentry:rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0"
```

```
k logs -n firewall droptailer-667bdd5598-rmrm7 -f
2021/02/11 18:35:22 listening on 50051


```

**Comment by majst01** [comment]
This has been fixed with: https://github.com/metal-stack/gardener-extension-provider-metal/pull/136
I have trouble understanding how this happens now ?

**Comment by mwennrich** [comment]
```yaml
        Validity
            Not Before: Jan 15 09:46:43 2021 GMT
            Not After : Jan 15 09:46:43 2031 GMT
        Subject: O = droptailer-server, CN = droptailer
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
```

```yaml
        Validity
            Not Before: Jan 15 09:46:43 2021 GMT
            Not After : Jan 15 09:46:43 2031 GMT
        Subject: O = droptailer-client, CN = droptailer
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication
            X509v3 Basic Constraints: critical
```

there are still the old (wrong) certificates from the previous controller.
